### PR TITLE
Improved user tagging

### PR DESCRIPTION
**Pull request by CosmiX-6**
Improvement in kick, mute, unmute command:
Now user can be tagged using `@`.

### CODE REVIEW

**Comment by AnkithAbhayan** [comment]
interesting.. but would this work if I used the user id as well? 
I'd like it if both would work.
ping and user id.
Another thing worth noting is that most of the infractions are done in a Moderator-only channel resulting in the user getting a dm from the bot telling them why they got infracted. Since all users are not moderators, we cant ping them when muting them there. Which is where the feature to use both pings and user id comes into play.

**Comment by CosmiX-6** [comment]
It will work for both, with user id and also with @tag.

**Comment by AnkithAbhayan** [comment]
aight.

**Comment by AnkithAbhayan** [comment]
LGTM thanks!

**Pull request merged**
